/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2022-12-27 17:48:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import vo.ScheduleVO;
import vo.MovieVO;
import java.util.ArrayList;
import vo.MemberVO;

public final class movieInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project2_team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MovieMVC/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1672152264132L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project2_team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MovieMVC/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/view/../footer.jsp", Long.valueOf(1672160989975L));
    _jspx_dependants.put("/view/../header.jsp", Long.valueOf(1672163066289L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.MovieVO");
    _jspx_imports_classes.add("vo.ScheduleVO");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("vo.MemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>영화 예매</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/lib/style.css?after\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/lib/semantic.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"\r\n");
      out.write("	integrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- <script src=\"/lib/semantic.min.js\"></script> -->\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("</head>\r\n");

MemberVO user = (MemberVO) session.getAttribute("user");
int userStatus = 0;

if (user != null) {
	if (user.getId() != null) {
		userStatus = 1;
	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"ui container\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<nav id=\"main_navi\">\r\n");
      out.write("				<ul id=\"menu\">\r\n");
      out.write("					<li data-n=\"1\"><a href=\"/\">박스오피스</a></li>\r\n");
      out.write("					<!-- 이용안내-->\r\n");
      out.write("					<li data-n=\"2\"><a class=\"click_movie\" href=\"#\">장르별 영화</a>\r\n");
      out.write("						<ul class=\"sub\">\r\n");
      out.write("							<li><a class=\"genre1\" href=\"/movieList.do?cat_no=1\">액션</a></li>\r\n");
      out.write("							<li><a class=\"genre2\" href=\"/movieList.do?cat_no=2\">로맨스</a></li>\r\n");
      out.write("							<li><a class=\"genre3\" href=\"/movieList.do?cat_no=3\">공포</a></li>\r\n");
      out.write("							<li><a class=\"genre4\" href=\"/movieList.do?cat_no=4\">스릴러</a></li>\r\n");
      out.write("							<li><a class=\"genre5\" href=\"/movieList.do?cat_no=5\">애니메이션</a></li>\r\n");
      out.write("						</ul></li>       \r\n");
      out.write("					<!-- 전시-->\r\n");
      out.write("					<li data-n=\"3\"><a href=\"/review.do\">리뷰</a> <!-- 프로그램--> <!-- 나만의 페이지-->\r\n");
      out.write("				</ul>\r\n");
      out.write("				<!--menu-->\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("			");

			if (userStatus == 1) {
				if (user.getId().equals("admin")) {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"right item\">\r\n");
      out.write("				<p style=\"margin: 0 15px;\">");
      out.print(user.getId());
      out.write("님\r\n");
      out.write("				</p>\r\n");
      out.write("				<div class=\"ui primary button\"\r\n");
      out.write("					onclick=\"location.href = '/view/register.jsp';\">영화 추가</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<div class=\"ui button\"\r\n");
      out.write("					onclick=\"location.href = '/view/myTickets.jsp';\">전체 예메목록</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<div class=\"ui button\"\r\n");
      out.write("					onclick=\"swal('Success', '로그아웃 성공', 'success').then((val) => {location.href = '/view/logout.jsp';});\">로그아웃</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"right item\">\r\n");
      out.write("				<p class=\"user_id\">");
      out.print(user.getId());
      out.write("님</p>\r\n");
      out.write("				<div class=\"mypage ui primary button\"\r\n");
      out.write("					onclick=\"location.href = '/view/myTickets.jsp';\">마이페이지</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<div class=\"logout ui button\"\r\n");
      out.write("					onclick=\"swal('Success', '로그아웃 성공', 'success').then((val) => {location.href = '/view/logout.jsp';});\">로그아웃</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			");

			}
			} else {
			
      out.write("\r\n");
      out.write("			<ul class=\"quick\">\r\n");
      out.write("				<li onclick=\"location.href = '/view/register.jsp';\">회원가입</li>\r\n");
      out.write("				<li onclick=\"location.href = '/view/login.jsp';\">로그인</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function () {\r\n");
      out.write("		  //태그 추가\r\n");
      out.write("		  $(\"#main_navi\").before(\"<div class='bg'></div>\");\r\n");
      out.write("		  $(\".bg,.sub\").hide();\r\n");
      out.write("		  $(\"#menu\")\r\n");
      out.write("		    .mouseenter(function() {\r\n");
      out.write("		      $(\".bg\").stop().slideDown(\"fast\");\r\n");
      out.write("		      $(\".sub\").stop().show();\r\n");
      out.write("		    })\r\n");
      out.write("		    .mouseleave(function() {\r\n");
      out.write("		      $(\".bg\").stop().slideUp(\"fast\");\r\n");
      out.write("		      $(\".sub\").stop().hide();\r\n");
      out.write("		    });\r\n");
      out.write("		  $(\".bg\")\r\n");
      out.write("		    .mouseover(function() {\r\n");
      out.write("		      $(this).stop().show();\r\n");
      out.write("		      $(\".sub\").stop().show();\r\n");
      out.write("		    })\r\n");
      out.write("		    .mouseout(function() {\r\n");
      out.write("		      $(this).stop().slideUp();\r\n");
      out.write("		      $(\".sub\").stop().slideUp();\r\n");
      out.write("		    });\r\n");
      out.write("		  \r\n");
      out.write("		  $(\".click_movie\").click(function() {\r\n");
      out.write("			  $(\".bg\").stop().slideDown(\"fast\");\r\n");
      out.write("		      $(\".sub\").stop().show();\r\n");
      out.write("		  }).dblclick(function() {\r\n");
      out.write("			  $(\".bg\").stop().slideUp(\"fast\");\r\n");
      out.write("		      $(\".sub\").stop().hide();\r\n");
      out.write("		  });\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");

	MovieVO movieInfo = new MovieVO();
	ArrayList<ScheduleVO> schList = new ArrayList<ScheduleVO>();
	
	if(request.getAttribute("movieInfo") == null) {
		response.sendRedirect("/");
	}else {
		movieInfo = (MovieVO) request.getAttribute("movieInfo");
		schList = (ArrayList) request.getAttribute("scheduleAList");
	}
	
	String cat = "";
	String img = "";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"ui container\">\r\n");
      out.write("    <div class=\"visual\">\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <h2 class=\"movieinfo_title\">영화 정보</h2>\r\n");
      out.write("\r\n");
      out.write("		<table class=\"category ui inverted gray table movieInfoTable\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>영화 번호</th>\r\n");
      out.write("					<th>카테고리</th>\r\n");
      out.write("					<th>제목</th>\r\n");
      out.write("					<th>영화 정보</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				");

					img = movieInfo.getImg();	
					switch (movieInfo.getCategory()) {
					case 1:
						cat = "액션";
						break;
					case 2:
						cat = "로맨스";
						break;
					case 3:
						cat = "코미디";
						break;
					case 4:
						cat = "스릴러";
						break;
					case 5:
						cat = "애니메이션";
						break;
					}
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>No.");
      out.print(movieInfo.getMovieNo());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(cat);
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(movieInfo.getMovieName());
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(movieInfo.getInfo());
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<h2 class=\"viewingtime_title\" style=\"border-left: 2px solid #333; padding-left: 2px;\">관람 시간 선택</h2>\r\n");
      out.write("		<p class=\"viewingtime_script\">Tip: 원하는 관람 시간대에 클릭하면 좌석 선택 페이지로 이동됩니다.</p>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"movieInfoBox\">\r\n");
      out.write("			<div class=\"leftBox\">\r\n");
      out.write("				<img src=\"/images/");
      out.print(img);
      out.write("\" alt=\"");
      out.print(img);
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"rightBox\">\r\n");
      out.write("				<table class=\"ui inverted table\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>스케줄 번호</th>\r\n");
      out.write("							<th>상영날짜</th>\r\n");
      out.write("							<th>상영 시간</th>\r\n");
      out.write("							<th>상영관</th>\r\n");
      out.write("							<th>잔여석</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");

						for (ScheduleVO item : schList) {
							SimpleDateFormat sdf = new SimpleDateFormat("yyyy년 MM월 dd일 (HH시 mm분)");
							String datetime = sdf.format(item.getRunDay());
						
      out.write("\r\n");
      out.write("						<tr onclick=\"location.href = '/chooseSeat.do?schNo=");
      out.print(item.getSchNo());
      out.write("&roomNo=");
      out.print(item.getRoomNo() );
      out.write("';\">\r\n");
      out.write("							<td>No.");
      out.print(item.getSchNo() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(datetime );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getRuntime() );
      out.write("분</td>\r\n");
      out.write("							<td>");
      out.print(item.getRoomNo() );
      out.write("관</td>\r\n");
      out.write("							<td>");
      out.print(25 - item.getSeatCnt() );
      out.write("석</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");

							}
						
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/lib/style.css?after\">\r\n");
      out.write("<div id=\"bottom_wrap\">\r\n");
      out.write("    <footer id=\"bottom\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li><a href=\"#\">3조소개</a></li>\r\n");
      out.write("        <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("        <li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("        <li><a href=\"#\">영상정보처리기기</a></li>\r\n");
      out.write("        <li><a href=\"#\">운영관리 방침</a></li>\r\n");
      out.write("        <li><a href=\"#\">부정비리신고</a></li>\r\n");
      out.write("        <li><a href=\"#\">찾아오시는길</a></li>\r\n");
      out.write("        <li><a href=\"#\">이메일주소 수집거부</a></li>\r\n");
      out.write("        <li><a href=\"#\">원격연결</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <address class=\"add\">\r\n");
      out.write("        TEL:(02)2124-3114<br />\r\n");
      out.write("        <span class=\"add_sub\">07242 경기도 안산시 상록구</span>\r\n");
      out.write("      </address>\r\n");
      out.write("      <p>Copyright &copy; 2022 KBIZ All rights Reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
