/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2022-12-28 11:47:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.MovieVO;
import java.util.ArrayList;
import vo.MemberVO;

public final class movieList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project2_team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MovieMVC/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1672152264132L));
    _jspx_dependants.put("jar:file:/C:/ThisIsJavaSecondEdition/eclipse-workspace/project2_team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MovieMVC/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/view/../footer.jsp", Long.valueOf(1672160989975L));
    _jspx_dependants.put("/view/../header.jsp", Long.valueOf(1672225059861L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.MovieVO");
    _jspx_imports_classes.add("vo.MemberVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/lib/list.css?after\">\r\n");
      out.write(" <script src=\"../lib/jquery-3.6.1.min.js\"></script> \r\n");
      out.write("<script src=\"../lib/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script src=\"../lib/jquery-ui-1.10.4.custom.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>영화 예매</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/lib/style.css?after\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/lib/semantic.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"\r\n");
      out.write("	integrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- <script src=\"/lib/semantic.min.js\"></script> -->\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("</head>\r\n");

MemberVO user = (MemberVO) session.getAttribute("user");
int userStatus = 0;

if (user != null) {
	if (user.getId() != null) {
		userStatus = 1;
	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"ui container\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<nav id=\"main_navi\">\r\n");
      out.write("				<ul id=\"menu\">\r\n");
      out.write("					<li data-n=\"1\"><a href=\"/\">박스오피스</a></li>\r\n");
      out.write("					<!-- 이용안내-->\r\n");
      out.write("					<li data-n=\"2\"><a class=\"click_movie\" href=\"#\">장르별 영화</a>\r\n");
      out.write("						<ul class=\"sub\">\r\n");
      out.write("							<li><a class=\"genre1\" href=\"/movieList.do?cat_no=1\">액션</a></li>\r\n");
      out.write("							<li><a class=\"genre2\" href=\"/movieList.do?cat_no=2\">로맨스</a></li>\r\n");
      out.write("							<li><a class=\"genre3\" href=\"/movieList.do?cat_no=3\">공포</a></li>\r\n");
      out.write("							<li><a class=\"genre4\" href=\"/movieList.do?cat_no=4\">스릴러</a></li>\r\n");
      out.write("							<li><a class=\"genre5\" href=\"/movieList.do?cat_no=5\">애니메이션</a></li>\r\n");
      out.write("						</ul></li>       \r\n");
      out.write("					<!-- 전시-->\r\n");
      out.write("					<li data-n=\"3\"><a href=\"/review.do\">리뷰</a> <!-- 프로그램--> <!-- 나만의 페이지-->\r\n");
      out.write("				</ul>\r\n");
      out.write("				<!--menu-->\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("			");

			if (userStatus == 1) {
				if (user.getId().equals("admin")) {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"right item\">\r\n");
      out.write("				<p style=\"margin: 0 15px;\">");
      out.print(user.getId());
      out.write("님\r\n");
      out.write("				</p>\r\n");
      out.write("				<div class=\"ui primary button\"\r\n");
      out.write("					onclick=\"location.href = '/view/register.jsp';\">영화 추가</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<div class=\"ui button\"\r\n");
      out.write("					onclick=\"location.href = '/view/myTickets.jsp';\">전체 예메목록</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<div class=\"ui button\"\r\n");
      out.write("					onclick=\"swal('Success', '로그아웃 성공', 'success').then((val) => {location.href = '/view/logout.jsp';});\">로그아웃</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"right item\">\r\n");
      out.write("				<p class=\"user_id\">");
      out.print(user.getId());
      out.write("님</p>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<div class=\"logout ui button\"\r\n");
      out.write("					onclick=\"swal('Success', '로그아웃 성공', 'success').then((val) => {location.href = '/view/logout.jsp';});\">로그아웃</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			");

			}
			} else {
			
      out.write("\r\n");
      out.write("			<ul class=\"quick\">\r\n");
      out.write("				<li onclick=\"location.href = '/view/register.jsp';\">회원가입</li>\r\n");
      out.write("				<li onclick=\"location.href = '/view/login.jsp';\">로그인</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function () {\r\n");
      out.write("		  //태그 추가\r\n");
      out.write("		  $(\"#main_navi\").before(\"<div class='bg'></div>\");\r\n");
      out.write("		  $(\".bg,.sub\").hide();\r\n");
      out.write("		  $(\"#menu\")\r\n");
      out.write("		    .mouseenter(function() {\r\n");
      out.write("		      $(\".bg\").stop().slideDown(\"fast\");\r\n");
      out.write("		      $(\".sub\").stop().show();\r\n");
      out.write("		    })\r\n");
      out.write("		    .mouseleave(function() {\r\n");
      out.write("		      $(\".bg\").stop().slideUp(\"fast\");\r\n");
      out.write("		      $(\".sub\").stop().hide();\r\n");
      out.write("		    });\r\n");
      out.write("		  $(\".bg\")\r\n");
      out.write("		    .mouseover(function() {\r\n");
      out.write("		      $(this).stop().show();\r\n");
      out.write("		      $(\".sub\").stop().show();\r\n");
      out.write("		    })\r\n");
      out.write("		    .mouseout(function() {\r\n");
      out.write("		      $(this).stop().slideUp();\r\n");
      out.write("		      $(\".sub\").stop().slideUp();\r\n");
      out.write("		    });\r\n");
      out.write("		  \r\n");
      out.write("		  $(\".click_movie\").click(function() {\r\n");
      out.write("			  $(\".bg\").stop().slideDown(\"fast\");\r\n");
      out.write("		      $(\".sub\").stop().show();\r\n");
      out.write("		  }).dblclick(function() {\r\n");
      out.write("			  $(\".bg\").stop().slideUp(\"fast\");\r\n");
      out.write("		      $(\".sub\").stop().hide();\r\n");
      out.write("		  });\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<MovieVO> list = new ArrayList<MovieVO>();

	if(request.getAttribute("movieList") == null) {
		response.sendRedirect("movieList.do");
	}else {
		list = (ArrayList) request.getAttribute("movieList");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"ui container\">\r\n");
      out.write("        <!-- <img src=\"./images/logo.jpg\" alt=\"visualImg\"> -->\r\n");
      out.write("       <div class=\"visual\">\r\n");
      out.write("        <!-- <img src=\"./images/logo.jpg\" alt=\"visualImg\"> -->\r\n");
      out.write("         <div id=\"appletv_post\">\r\n");
      out.write("      <div class=\"appletv_post_con\">\r\n");
      out.write("     \r\n");
      out.write("      <div id=\"atv_p\">\r\n");
      out.write("        <div id=\"atv_wrap\">\r\n");
      out.write("          <ul class=\"atv\">\r\n");
      out.write("            <li class=\"no_1\" data-n=\"1\"><a href=\"#\"><img src=\"https://img.newspim.com/news/2020/04/13/2004130813526320.jpg\" alt=\"럭 포스터\" width=\"688\" height=\"387\"></a></li>\r\n");
      out.write("            <li class=\"no_2\" data-n=\"2\"><a href=\"#\"><img src=\"https://image.kmib.co.kr/online_image/2022/0107/2022010620211463553_1641468075_0924226465.jpg\" alt=\"테드 래소 포스터\" width=\"688\" height=\"387\"></a></li>\r\n");
      out.write("            <li class=\"no_3\" data-n=\"3\"><a href=\"#\"><img src=\"https://img3.daumcdn.net/thumb/R658x0.q70/?fname=https://t1.daumcdn.net/news/202211/04/tvdaily/20221104093722155qeis.jpg\" alt=\"DR.브레인 포스터\" width=\"688\" height=\"387\"></a></li>\r\n");
      out.write("            <!-- <li class=\"no_4\" data-n=\"4\"><a href=\"#\"><img src=\"http://talkimg.imbc.com/TVianUpload/tvian/TViews/image/2022/09/29/21c8e0c9-b498-4595-9ca4-5579a95221c2.jpg\" alt=\"인베이션 포스터\" width=\"688\" height=\"387\"></a></li>\r\n");
      out.write("            <li class=\"no_5\" data-n=\"5\"><a href=\"#\"><img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIUJQfG8lpVdxBnvZKeHbNiWSFFQgYqQNTkQ&usqp=CAU\" alt=\"세브란스:단절 포스터\" width=\"688\" height=\"387\"></a></li>\r\n");
      out.write("            <li class=\"no_6\" data-n=\"6\"><a href=\"#\"><img src=\"https://img.asiatoday.co.kr/file/2022y/08m/15d/2022081501001398400084201.jpg\" alt=\"SEE 어둠의 나날 포스터\" width=\"688\" height=\"387\"></a></li> -->\r\n");
      out.write("          </ul><!--atv-->\r\n");
      out.write("        </div><!--atv_wrap-->\r\n");
      out.write("      </div><!--atv_p-->\r\n");
      out.write("      <p class=\"prev\"><img src=\"../images/prev.png\" alt=\"이전버튼\" width=\"33\" height=\"62\"></p>\r\n");
      out.write("      <p class=\"next\"><img src=\"../images/next.png\" alt=\"다음버튼\" width=\"33\" height=\"62\"></p>\r\n");
      out.write("      </div><!--appletv_post_con-->\r\n");
      out.write("    </div><!--#appletv_post/애플 광고 전체-->\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <h2>전체 영화 목록</h2>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"MovieList\">\r\n");
      out.write("            <div class=\"ui link cards unit\">\r\n");
      out.write("            ");

				for (MovieVO vo : list) {
					String cat = "";
					
					switch (vo.getCategory()) {
						case 1 :
							cat = "액션";
							break;
						case 2 :
							cat = "로맨스";
							break;
						case 3 :
							cat = "코미디";
							break;
						case 4 :
							cat = "스릴러";
							break;
						case 5 :
							cat = "애니메이션";
							break;
					}
			
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <div class=\"movie-card\">\r\n");
      out.write("		<div class=\"movie-header avengers\">\r\n");
      out.write("			<div class=\"header-icon-container\">\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("				\r\n");
      out.write("				</a>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div><!--movie-header-->\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"movie-content\" onclick=\"location.href = '/reviewList.do?movieNo=");
      out.print(vo.getMovieNo());
      out.write("';\";>\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"movie-content-header\">\r\n");
      out.write("			<img alt=\"\" src=\"");
      out.print(vo.getImg());
      out.write("\">\r\n");
      out.write("				<a href=\"#\">\r\n");
      out.write("					<h3 class=\"movie-title\">");
      out.print(vo.getMovieName() );
      out.write("</h3>\r\n");
      out.write("				</a>\r\n");
      out.write("				<div class=\"imax-logo\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"movie-info\">\r\n");
      out.write("				<div class=\"info-section\">\r\n");
      out.write("					<label>장르</label>\r\n");
      out.write("					<span>");
      out.print(cat );
      out.write("	</span>\r\n");
      out.write("				</div><!--date,time-->\r\n");
      out.write("				<div class=\"info-section\">\r\n");
      out.write("					<label>상영시간</label>\r\n");
      out.write("					<span>");
      out.print(vo.getRuntime() );
      out.write("</span>\r\n");
      out.write("				</div><!--screen-->\r\n");
      out.write("				<div class=\"info-section\">\r\n");
      out.write("					<label>영화번호</label>\r\n");
      out.write("					<span>");
      out.print(vo.getMovieNo() );
      out.write("</span>\r\n");
      out.write("				</div><!--row-->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div><!--movie-content-->\r\n");
      out.write("	</div><!--movie-card-->\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("	function banner() {\r\n");
      out.write("\r\n");
      out.write("		$(\".atv:not(:animated)\").animate({\r\n");
      out.write("			marginLeft : parseInt($(\".atv\").css(\"margin-left\")) - 688 + \"px\"\r\n");
      out.write("		}, \"slow\", \"swing\", function() {\r\n");
      out.write("			$(\".atv li:first\").appendTo(\".atv\");\r\n");
      out.write("			$(\".atv\").css(\"margin-left\", \"-688px\");\r\n");
      out.write("			var n = $(\".atv li\").attr(\"data-n\");\r\n");
      out.write("			n++;\r\n");
      out.write("			if (n == 7) {\r\n");
      out.write("				n = 1;\r\n");
      out.write("			}\r\n");
      out.write("			$(\"#appletv_post\").removeClass();\r\n");
      out.write("			$(\"#appletv_post\").addClass(\"bg\" + n).animate({\r\n");
      out.write("				\"transition\" : \".9s\"\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	$(document)\r\n");
      out.write("			.ready(\r\n");
      out.write("					function() {\r\n");
      out.write("						\r\n");
      out.write("						// 포스터 자동슬라이드\r\n");
      out.write("						// var li_w = $(\".atv li\").width();\r\n");
      out.write("						var w = 690 * $(\".atv li\").length + \"px\";\r\n");
      out.write("						$(\".atv\").css(\"width\", w);\r\n");
      out.write("						$(\".atv li:last\").prependTo(\".atv\");\r\n");
      out.write("						$(\".atv\").css(\"margin-left\", \"-690px\");\r\n");
      out.write("\r\n");
      out.write("						$(\"#appletv_post\").addClass(\"bg1\");\r\n");
      out.write("\r\n");
      out.write("						$(\".prev\").click(\r\n");
      out.write("								function() {// <\r\n");
      out.write("									$(\".atv:not(:animated)\").animate(\r\n");
      out.write("											{\r\n");
      out.write("												marginLeft : parseInt($(\".atv\")\r\n");
      out.write("														.css(\"margin-left\"))\r\n");
      out.write("														- 690 + \"px\"\r\n");
      out.write("											},\r\n");
      out.write("											function() {\r\n");
      out.write("												$(\".atv li:first\").appendTo(\r\n");
      out.write("														\".atv\");\r\n");
      out.write("												$(\".atv\").css(\"margin-left\",\r\n");
      out.write("														\"-690px\")\r\n");
      out.write("\r\n");
      out.write("												var n = $(\".atv li\").attr(\r\n");
      out.write("														\"data-n\");\r\n");
      out.write("												n++;\r\n");
      out.write("												if (n == 7) {\r\n");
      out.write("													n = 1;\r\n");
      out.write("												}\r\n");
      out.write("												$(\"#appletv_post\")\r\n");
      out.write("														.removeClass();\r\n");
      out.write("												$(\"#appletv_post\").addClass(\r\n");
      out.write("														\"bg\" + n).animate({\r\n");
      out.write("													\"transition\" : \".9s\"\r\n");
      out.write("												});\r\n");
      out.write("											});\r\n");
      out.write("								});\r\n");
      out.write("						$(\".next\").click(\r\n");
      out.write("								function() {// >\r\n");
      out.write("									$(\".atv:not(:animated)\").animate(\r\n");
      out.write("											{\r\n");
      out.write("												marginLeft : parseInt($(\".atv\")\r\n");
      out.write("														.css(\"margin-left\"))\r\n");
      out.write("														+ 690 + \"px\"\r\n");
      out.write("											},\r\n");
      out.write("											function() {\r\n");
      out.write("												$(\".atv li:last\").prependTo(\r\n");
      out.write("														\".atv\");\r\n");
      out.write("												$(\".atv\").css(\"margin-left\",\r\n");
      out.write("														\"-690px\");\r\n");
      out.write("\r\n");
      out.write("												var n = $(\".atv li\").attr(\r\n");
      out.write("														\"data-n\");\r\n");
      out.write("												n++;\r\n");
      out.write("												if (n == 7) {\r\n");
      out.write("													n = 1;\r\n");
      out.write("												}\r\n");
      out.write("												$(\"#appletv_post\")\r\n");
      out.write("														.removeClass();\r\n");
      out.write("												$(\"#appletv_post\").addClass(\r\n");
      out.write("														\"bg\" + n).animate({\r\n");
      out.write("													\"transition\" : \".9s\"\r\n");
      out.write("												});\r\n");
      out.write("											});\r\n");
      out.write("								});\r\n");
      out.write("						var banner = setInterval(\"banner()\", 3000);\r\n");
      out.write("\r\n");
      out.write("						$(\".atv li\").mouseover(function() {\r\n");
      out.write("							clearInterval(banner);\r\n");
      out.write("							$(this).find(\"img\").css(\"opacity\", \"0.5\");\r\n");
      out.write("						}).mouseout(function() {\r\n");
      out.write("							banner = setInterval(\"banner()\", 3000);\r\n");
      out.write("							$(this).find(\"img\").css(\"opacity\", \"1.0\");\r\n");
      out.write("						});\r\n");
      out.write("						$(\".next\").mouseover(function() {\r\n");
      out.write("							clearInterval(banner);\r\n");
      out.write("							$(this).find(\"img\").css(\"opacity\", \"0.5\");\r\n");
      out.write("						}).mouseout(function() {\r\n");
      out.write("							banner = setInterval(\"banner()\", 3000);\r\n");
      out.write("							$(this).find(\"img\").css(\"opacity\", \"1.0\");\r\n");
      out.write("						});\r\n");
      out.write("						$(\".prev\").mouseover(function() {\r\n");
      out.write("							clearInterval(banner);\r\n");
      out.write("							$(this).find(\"img\").css(\"opacity\", \"0.5\");\r\n");
      out.write("						}).mouseout(function() {\r\n");
      out.write("							banner = setInterval(\"banner()\", 3000);\r\n");
      out.write("							$(this).find(\"img\").css(\"opacity\", \"1.0\");\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						$(\".s_se\").mouseover(\r\n");
      out.write("								function() {\r\n");
      out.write("									$(this).attr(\"src\",\r\n");
      out.write("											\"images/iphone_se_cut_large.jpg\")\r\n");
      out.write("											.css(\"width\", \"151\").css(\"height\",\r\n");
      out.write("													\"257\");\r\n");
      out.write("								}).mouseout(\r\n");
      out.write("								function() {\r\n");
      out.write("									$(this).attr(\"src\",\r\n");
      out.write("											\"images/iphone_se_cut_medium.jpg\")\r\n");
      out.write("											.css(\"width\", \"119\").css(\"height\",\r\n");
      out.write("													\"204\");\r\n");
      out.write("								});\r\n");
      out.write("						$(\".s_13\").mouseover(\r\n");
      out.write("								function() {\r\n");
      out.write("									$(this).attr(\"src\",\r\n");
      out.write("											\"images/iphone_13_cut_large.jpg\")\r\n");
      out.write("											.css(\"width\", \"161\").css(\"height\",\r\n");
      out.write("													\"257\");\r\n");
      out.write("								}).mouseout(\r\n");
      out.write("								function() {\r\n");
      out.write("									$(this).attr(\"src\",\r\n");
      out.write("											\"images/iphone_13_cut_medium.jpg\")\r\n");
      out.write("											.css(\"width\", \"128\").css(\"height\",\r\n");
      out.write("													\"204\");\r\n");
      out.write("								});\r\n");
      out.write("						$(\".s_14\").mouseover(\r\n");
      out.write("								function() {\r\n");
      out.write("									$(this).attr(\"src\",\r\n");
      out.write("											\"images/iphone_14_cut_large.jpg\")\r\n");
      out.write("											.css(\"width\", \"180\").css(\"height\",\r\n");
      out.write("													\"257\");\r\n");
      out.write("								}).mouseout(\r\n");
      out.write("								function() {\r\n");
      out.write("									$(this).attr(\"src\",\r\n");
      out.write("											\"images/iphone_14_cut_medium.jpg\")\r\n");
      out.write("											.css(\"width\", \"143\").css(\"height\",\r\n");
      out.write("													\"204\");\r\n");
      out.write("								});\r\n");
      out.write("						$(\".s_14pro\")\r\n");
      out.write("								.mouseover(\r\n");
      out.write("										function() {\r\n");
      out.write("											$(this)\r\n");
      out.write("													.attr(\"src\",\r\n");
      out.write("															\"images/iphone_14_pro_cut_large.jpg\")\r\n");
      out.write("													.css(\"width\", \"190\").css(\r\n");
      out.write("															\"height\", \"257\");\r\n");
      out.write("										})\r\n");
      out.write("								.mouseout(\r\n");
      out.write("										function() {\r\n");
      out.write("											$(this)\r\n");
      out.write("													.attr(\"src\",\r\n");
      out.write("															\"images/iphone_14_pro_cut_medium.jpg\")\r\n");
      out.write("													.css(\"width\", \"151\").css(\r\n");
      out.write("															\"height\", \"204\");\r\n");
      out.write("										});\r\n");
      out.write("\r\n");
      out.write("					});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/lib/style.css?after\">\r\n");
      out.write("<div id=\"bottom_wrap\">\r\n");
      out.write("    <footer id=\"bottom\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li><a href=\"#\">3조소개</a></li>\r\n");
      out.write("        <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("        <li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("        <li><a href=\"#\">영상정보처리기기</a></li>\r\n");
      out.write("        <li><a href=\"#\">운영관리 방침</a></li>\r\n");
      out.write("        <li><a href=\"#\">부정비리신고</a></li>\r\n");
      out.write("        <li><a href=\"#\">찾아오시는길</a></li>\r\n");
      out.write("        <li><a href=\"#\">이메일주소 수집거부</a></li>\r\n");
      out.write("        <li><a href=\"#\">원격연결</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <address class=\"add\">\r\n");
      out.write("        TEL:(02)2124-3114<br />\r\n");
      out.write("        <span class=\"add_sub\">07242 경기도 안산시 상록구</span>\r\n");
      out.write("      </address>\r\n");
      out.write("      <p>Copyright &copy; 2022 KBIZ All rights Reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
